# Generated by Django 5.1 on 2024-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="exp",
            field=models.TextField(blank=True, null=True),
        ),
    ]
